### ISSUE TITLE
atomic transaction

### ISSUE THREAD

**Issue by nordbit** [eldest-daughter/ed-questionnaire#12]
TransactionManagementError at /q/3b29810cb6f1d567b9f1ea2a2c316d81/1/
This is forbidden when an 'atomic' block is active.

Django 1.6.11, Python 2.7

**Comment by nordbit** [comment]
Sorry, I forgot uninstall old original questionnaire from eggs

**Comment by gcaprio** [comment]
@nordbit No problem, thanks for checking.
