### ISSUE TITLE
help message about "textile" is wrong

### ISSUE THREAD

**Issue by eshellman** [eldest-daughter/ed-questionnaire#18]
the help_text for models.QuestionSet is wrong https://github.com/eldest-daughter/ed-questionnaire/blob/master/questionnaire/models.py#L101

Perhaps some previous version implemented filters?

I see that the draconicfae fork has addressed this. is this fork being maintained?

**Comment by gcaprio** [comment]
No , sadly this fork should be considered EOL'd as of now.
