### ISSUE TITLE
CSV functionality is not working Properly

### ISSUE THREAD

**Issue by mpetyx** [eldest-daughter/ed-questionnaire#19]
the csv that my app downloads, is just an empty csv.. any idea what may happen..?

**Comment by ingodjango** [comment]
What django version are you using? And which version of the questionaire?

**Comment by mpetyx** [comment]
django==1.8.5 and the latest version of the questionaire from the github

**Comment by ingodjango** [comment]
okay with 1.9 it has another issue, so I replaced the methode export_cvs in views.py with that:
`@permission_required("questionnaire.export")
def export_csv(request, qid):  # questionnaire_id
    """
    For a given questionnaire id, generaete a CSV containing all the
    answers for all subjects.
    """
    import csv
   
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')

    writer = csv.writer(response, dialect=csv.excel)
    
    questionnaire = get_object_or_404(Questionnaire, pk=int(qid))
    headings, answers = answer_export(questionnaire)

    writer.writerow([u'subject', u'runid'] + headings)
    for subject, runid, answer_row in answers:
        row = ["%s/%s" % (subject.id, subject.state), runid] + [
            a if a else '--' for a in answer_row]
        writer.writerow(row)

    response['Content-Disposition'] = 'attachment; filename="export-%s.csv"' % qid

    return response`

HTH

**Comment by mpetyx** [comment]
nice nice now it works! thank you very much!
